djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("news_website.urls", namespace="news_website")),
    path('', include('social_django.urls', namespace='social')),
]

news_website/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy


class MyHackedView(auth_views.PasswordResetView):
    success_url = reverse_lazy("news_website:password_reset_done")


app_name = "news_website"
urlpatterns = [
    path('news_type/<slug:slug>/', views.detailed_news_type, name='detailed_news_type'),
    path('', views.all_news_type, name='all_news_type'),
    path('<int:y>/<int:m>/<int:d>/<slug:slug>/', views.detailed_news,
         name="detailed_news"),
    path('<int:news_id>/share/', views.share_post, name="share_post"),

    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('password_reset/', MyHackedView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        success_url=reverse_lazy("news_website:password_reset_complete"),
    ), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    path('password-change/', auth_views.PasswordChangeView.as_view(
        success_url=reverse_lazy("news_website:password_change_done"),
    ), name='password_change'),
    path('password-change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    path('profile/', views.profile, name='profile'),
    path('register/', views.register, name='register'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),



]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

news_website/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


# Create your models here.


class News(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255,
                            unique_for_date="publish")

    body = models.TextField()

    publish = models.DateTimeField(default=timezone.now)

    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="author_materials")

    title_image = models.ImageField(upload_to="post/%Y/%m/%d",)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("news_website:detailed_news",
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):

    name = models.CharField(max_length=255)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    material = models.ForeignKey(News,
                                 on_delete=models.CASCADE,
                                 related_name='comments')

    def __str__(self):
        return '@{name} {body} for {material}'.format(name=self.name,
                                                      body=self.body,
                                                      material=self.material)


class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL,
                                on_delete=models.CASCADE)
    photo = models.ImageField(upload_to="user/%Y/%m/%d", blank=True)


class NewsType(models.Model):
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, unique=True)
    description = models.TextField()
    news = models.ManyToManyField(News, related_name='news')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('news_website:detailed_news_type',
                       args=[self.slug])

news_website/forms.py
from django import forms
from . import models

from django.contrib.auth.models import User


class EmailMaterialForm(forms.Form):
    name = forms.CharField()
    send_adres = forms.EmailField()


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class CommentForm(forms.ModelForm):
    class Meta:
        model = models.Comment
        fields = ('body', )


class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Pass', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Pass2', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('bad password')
        return cd['password']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = ('photo', )

news_website/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from . import models
from . import forms
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.contrib import auth
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.

SUBJECT = "{name} Хочет показать рассказать вам новость {title}."
BODY = ("{title} at {uri}. {name} отправил вам новость. "
        "Пожалуйста, посмотрите её "  ".")


@login_required()
def detailed_news(request, y, m, d, slug):
    news = get_object_or_404(models.News,
                             publish__year=y,
                             publish__month=m,
                             publish__day=d,
                             slug=slug)
    if request.method == "POST":
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.name = auth.get_user(request)
            comment.material = news
            comment.save()
            return redirect(news)

    else:
        form = forms.CommentForm()

    return render(request, "news/detailed_news.html",
                  {"news": news, 'form': form})


def share_post(request, news_id,):
    news = get_object_or_404(models.News, id=news_id)

    sent = False

    if request.method == "POST":
        form = forms.EmailMaterialForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            uri = request.build_absolute_uri(
                news.get_absolute_url(),
            )

            subject = SUBJECT.format(name=cd['name'],
                                     title=news.title)
            body = BODY.format(title=news.title,
                               uri=uri,
                               name=cd['name'],
                               )

            send_mail(subject, body, 'admin@my.com', [cd['send_adres'], ])
            sent = True
    else:
        form = forms.EmailMaterialForm()

    return render(request,
                  "news/share.html",
                  {'news': news, 'form': form, 'sent': sent})


def profile(request):
    return render(request, "profile.html", {'user': request.user})


def register(request):
    if request.method == "POST":
        form = forms.UserRegistrationForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            new_user = form.save(commit=False)
            new_user.set_password(cd['password'])
            new_user.save()
            models.Profile.objects.create(user=new_user, photo='unknown.jpg')

            return render(request, "registration_complete.html",
                          {"user": new_user})

    else:
        form = forms.UserRegistrationForm()
        return render(request, "register.html", {'form': form})


def edit_profile(request):
    if request.method == "POST":
        user_form = forms.UserEditForm(request.POST, instance=request.user)
        profile_form = forms.ProfileEditForm(request.POST,
                                             instance=request.user.profile,
                                             files=request.FILES)
        if all((user_form.is_valid(), profile_form.is_valid())):
            user_form.save()
            if not profile_form.cleaned_data['photo']:
                profile_form.cleaned_data['photo'] = request.user.profile.photo
            profile_form.save()
            return render(request, "profile.html", {'user': request.user})

    else:
        user_form = forms.UserEditForm(instance=request.user)
        profile_form = forms.ProfileEditForm(request.POST, instance=request.user.profile)

    return render(request, "edit_profile.html", {'user_form': user_form,
                                                 'profile_form': profile_form})


def all_news_type(request):
    query = request.GET.get("q", "")
    if query:
        news_type = models.NewsType.objects.all()
        news = models.News.objects.filter(Q(title__icontains=query) | Q(body__icontains=query))

    else:
        news_type = models.NewsType.objects.all()
        news = models.News.objects.all()

    paginator = Paginator(news, 2)
    page = request.GET.get('page', 1)

    try:
        news = paginator.get_page(page)
    except PageNotAnInteger:
        news = paginator.page(1)
    except EmptyPage:
        news = paginator.page(paginator.num_pages)

    return render(request, "news_type/all_news_type.html",
                    {"news_type": news_type, "news": news, "page": page})


def detailed_news_type(request, slug):
    news_type = get_object_or_404(models.NewsType, slug=slug)

    news_types = models.NewsType.objects.all()

    return render(request, "news_type/detailed_news_type.html",
                  {"news_type": news_type, 'news_types': news_types})

news_website/templates/base.html
{% load bootstrap4 %}
{% load static %}
{% bootstrap_css %}
{% bootstrap_javascript %}



<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}MY NEWS BLOG{% endblock %}</title>

</head>

<body>
{#header#}
    <header>
    <nav class="navbar navbar-light bg-light">
      <span class="navbar-brand mb-0 h1">Мой новостной блог</span>
        <form action="{% url 'news_website:all_news_type' %}" method="get">
            <input name="q" type="text" placeholder="Search...">
        </form>
        {% if request.user.is_authenticated %}
            <div class = "text-right">
                <a href="{% url "news_website:logout" %}">Выйти </a>
                <a href="{% url "news_website:profile" %}">Профиль </a>
            </div>
        {% else %}
            <div class = "text-right">
                <a href="{% url "news_website:login" %}">Войти </a>
                <a href="{% url "news_website:register" %}">Регистрация </a>
            </div>
        {% endif %}
    </nav>
    </header>
{#    navbar#}
    <nav class="navbar navbar-light bg-light">
        {% block nav %}{% endblock %}
    </nav>
{#mainbody#}
    <div class="row ">
        <div class="col"></div>
        <div class="col-8">
            {% block body %}{% endblock %}
        </div>
        <div class="col"></div>
    </div>

news_website/templates/edit_profile.html
{#{% extends 'base.html' %}#}

{% block title %}
    Изменить профиль
{% endblock %}

{% block body %}
        <h1>Вы можете изменить свои данные:</h1>
        <form action="." method="post" enctype="multipart/form-data">
            {{ user_form.as_p }}
            {{ profile_form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Изменить">
        </form>
{% endblock %}

news_website/templates/pagination.html
<div class="pagination">
     <span class="step-links">
          {% if page.has_previous %}
                <a href="?page={{ page.previous_page_number }}">Previous</a>
          {% endif %}
                <span class="current">
                    Page {{ page.number }} of {{ page.paginator.num_pages }}.
                </span>
          {% if page.has_next %}
                <a href="?page={{ page.next_page_number }}">Next</a>
          {% endif %}
      </span>
</div>

news_website/templates/profile.html
{% extends 'base.html' %}

{% block title %}
    Профиль
{% endblock %}

{% block body %}
       <div class="row ">
            <div class="col-2">
                <img src="{{ user.profile.photo.url }}" height="200"  alt="alt text" class="rounded-circle">
            </div>
            <div class="col">
                <p>Приветствую,{{ user.first_name }}, {{ user.last_name }}</p>
                <a href="{% url "news_website:edit_profile" %}">Изменить профиль </a><hr>
                <a href="{% url "news_website:password_change" %}">Сменить пароль </a><hr>
                <a href="{% url "news_website:all_news_type" %}"> Вернуться на главную </a><hr>
            </div>
        </div>
{% endblock %}

news_website/templates/register.html
{% extends 'base.html' %}

{% block title %}
Регистрация
{% endblock %}

{% block body %}
    <h1>Заполните поля</h1>
    <form action="." method="post">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" value="Регистрация">
    </form>
    <p class="mb-0"><a href="{% url "news_website:all_news_type" %}"> Вернуться на главную </a></p>
{% endblock %}

news_website/templates/registration_complete.html
{% extends 'base.html' %}

{% block title %}
    Регистрация завершена
{% endblock %}

{% block body %}
    <div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Отличная работа!{{ user.first_name }}</h4>
      <p>Теперь вы можете войти в свой профиль</p>
    <p><a href="{% url "news_website:login" %}">Логин </a></p>
     <hr>
  <p class="mb-0"><a href="{% url "news_website:all_news_type" %}"> Вернуться на главную </a></p>
    </div>
{% endblock %}